// Generated by nitro
import type { Serialize, Simplify } from 'nitropack/types'
declare module 'nitropack/types' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/health': {
      get: Simplify<
        Serialize<Awaited<ReturnType<typeof import('../../server/routes/health.get').default>>>
      >
    }
    '/ws': {
      default: Simplify<
        Serialize<Awaited<ReturnType<typeof import('../../server/routes/ws').default>>>
      >
    }
  }
}
export {}
